import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import toml from "esbuild-plugin-toml";

import path from "path";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const wasmPlugin = (config) => {
    return {
        name: "wasm",
        setup(build) {
            build.onResolve({ filter: /\.wasm$/ }, (args) => {
                if (args.resolveDir === "") {
                    return;
                }
                return {
                    path: path.isAbsolute(args.path)
                        ? args.path
                        : path.join(args.resolveDir, args.path),
                    namespace: `wasm-${config.mode}`,
                };
            });
            build.onLoad(
                { filter: /.*/, namespace: "wasm-deferred" },
                async (args) => ({
                    contents: await fs.promises.readFile(args.path),
                    loader: "file",
                })
            );
            build.onLoad(
                { filter: /.*/, namespace: "wasm-embed" },
                async (args) => ({
                    contents: await fs.promises.readFile(args.path),
                    loader: "binary",
                })
            );
        },
    };
};

const prod = process.argv[2] === "production";
const test_build = process.argv[2] === "test" || process.argv[3] === "test";

// Any arg that looks like an absolute path is the vault output directory
const vaultPath = process.argv.slice(2).find(
    (arg) => arg.includes(":\\") || (arg.startsWith("/") && arg.length > 1)
) ?? null;
const outDir = vaultPath ?? ".";

let entry_point;
let outfile;
if (!test_build) {
    entry_point = "src/main.ts";
    outfile = path.join(outDir, "main.js");
} else {
    entry_point = "tests/main.test.ts";
    outfile = path.join(outDir, "main.test.js");
}

// PURPOSE: Copy manifest.json and styles.css to vault plugin dir after each build
const copyAssetsPlugin = () => ({
    name: "copy-assets",
    setup(build) {
        build.onEnd(() => {
            if (!vaultPath) return;
            ["manifest.json", "styles.css"].forEach((file) => {
                if (fs.existsSync(file)) {
                    fs.copyFileSync(file, path.join(vaultPath, file));
                }
            });
        });
    },
});

esbuild
    .build({
        banner: {
            js: banner,
        },
        entryPoints: [entry_point],
        bundle: true,
        external: [
            "obsidian",
            "electron",
            "@codemirror/autocomplete",
            "@codemirror/closebrackets",
            "@codemirror/collab",
            "@codemirror/commands",
            "@codemirror/comment",
            "@codemirror/fold",
            "@codemirror/gutter",
            "@codemirror/highlight",
            "@codemirror/history",
            "@codemirror/language",
            "@codemirror/lint",
            "@codemirror/matchbrackets",
            "@codemirror/panel",
            "@codemirror/rangeset",
            "@codemirror/rectangular-selection",
            "@codemirror/search",
            "@codemirror/state",
            "@codemirror/stream-parser",
            "@codemirror/text",
            "@codemirror/tooltip",
            "@codemirror/view",
            ...builtins,
        ],
        format: "cjs",
        watch: !prod,
        target: "es2020",
        logLevel: "info",
        sourcemap: prod ? false : "inline",
        treeShaking: true,
        minify: prod,
        plugins: [toml(), wasmPlugin({ mode: "embed" }), copyAssetsPlugin()],
        outfile: outfile,
    })
    .catch(() => process.exit(1));
